### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by source99** [Anoncoin/oldrepo-backup#27]
makefile.unix is trying to build obj/bitcoinrpc.o but there are no source files with the same names...Trying to build on ubuntu 12.04.  Have built many other alt-coins

OBJS= \
    leveldb/libleveldb.a \
    ../i2psam/libi2psam.a \
    obj/alert.o \
    obj/version.o \
    obj/checkpoints.o \
    obj/netbase.o \
    obj/addrman.o \
    obj/crypter.o \
    obj/key.o \
    obj/db.o \
    obj/init.o \
    obj/keystore.o \
    obj/irc.o \
    obj/i2p.o \
    obj/main.o \
    obj/net.o \
    obj/protocol.o \
*\*    obj/bitcoinrpc.o \ **
    obj/rpcdump.o \
    obj/rpcnet.o \
    obj/rpcmining.o \
    obj/rpcwallet.o \
    obj/rpcblockchain.o \
    obj/rpcrawtransaction.o \
    obj/script.o \
    obj/scrypt.o \
    obj/sync.o \
    obj/util.o \
    obj/wallet.o \
    obj/walletdb.o \
    obj/hash.o \
    obj/bloom.o \
    obj/noui.o \
    obj/leveldb.o \
    obj/txdb.o \
    obj/miner.o

**Comment by source99** [comment]
I was able to go back a few commits to the "Fixing warning" - commit d99ac12f49cd12abacb574e9bbc8f15a72bf87a1 and it worked.

**Comment by Gnos1s** [comment]
Which commit were you on when you had this error?

**Comment by krypto-knight** [comment]
I suspect it's git HEAD as per issue #29.

**Comment by Gnos1s** [comment]
Please do a "git pull" then "make clean", and try again. If you are still having compilation errors, please open another issue.
